cd "assets"
Rename-Item "Imagem Intro.png" "imagem_intro.png"
Rename-Item "acima do peso pagina 4.jpg" "acima_do_peso_p4.jpg"
Rename-Item "antes e dps pagina 23.png" "antes_dps_p23.png"
Rename-Item "antes e dps pagina 33.png" "antes_dps_p33.png"
Rename-Item "antes pagina 12.png" "antes_p12.png"
Rename-Item "body medio pagina 4.jpg" "body_medio_p4.jpg"
Rename-Item "como usar gelatina mounjaro pagina 22.png" "como_usar_p22.png"
Rename-Item "corpo dos sonhos pagina 12.png" "corpo_sonhos_p12.png"
Rename-Item "corpo pagina 5.jpg" "corpo_p5.jpg"
Rename-Item "garantia 30 dias pagina 33.png" "garantia_30d_p33.png"
Rename-Item "gelatina pagina 12.png" "gelatina_p12.png"
Rename-Item "historia claudia pagina 27.png" "historia_claudia_p27.png"
Rename-Item "historia giovanna pagina 27.png" "historia_giovanna_p27.png"
Rename-Item "historia patricia pagina 27.png" "historia_patricia_p27.png"
Rename-Item "historia sandra pagina 27.png" "historia_sandra_p27.png"
Rename-Item "imagem pagina 2.jpg" "imagem_p2.jpg"
Rename-Item "logo mounjaro.png" "logo_mounjaro.png"
Rename-Item "maria antes e dps pagina 21.png" "maria_antes_dps_p21.png"
Rename-Item "otimo objetivo pagina 16.png" "otimo_objetivo_p16.png"
Rename-Item "pagina 33 oferta.jpg" "p33_oferta.jpg"
Rename-Item "plussize pagina 4.jpg" "plussize_p4.jpg"
Rename-Item "queima natural pagina 12.png" "queima_natural_p12.png"
Rename-Item "sobrepeso pagina 4.jpg" "sobrepeso_p4.jpg"
cd ..
