$c = Get-Content index.html -Raw -Encoding utf8
$c = $c.replace('assets/logo.png', 'assets/logo mounjaro.png')
$c = $c.replace('assets/hero.jpg', 'assets/Imagem Intro.png')
$c = $c.replace('assets/bowl.jpg', 'assets/imagem pagina 2.jpg')
$c = $c.replace('assets/body-medio.jpg', 'assets/body medio pagina 4.jpg')
$c = $c.replace('assets/body-plus.jpg', 'assets/plussize pagina 4.jpg')
$c = $c.replace('assets/body-acima.jpg', 'assets/acima do peso pagina 4.jpg')
$c = $c.replace('assets/body-sobrepeso.jpg', 'assets/sobrepeso pagina 4.jpg')
$c = $c.replace('assets/body-target.jpg', 'assets/corpo pagina 5.jpg')
$c = $c.replace('assets/antes.png', 'assets/antes pagina 12.png')
$c = $c.replace('assets/antes-depois.png', 'assets/corpo dos sonhos pagina 12.png')
$c = $c.replace('assets/gelatina-icon.png', 'assets/gelatina pagina 12.png')
$c = $c.replace('assets/corpo-icon.png', 'assets/queima natural pagina 12.png')
$c = $c.replace('assets/otimo-objetivo.png', 'assets/otimo objetivo pagina 16.png')
$c = $c.replace('assets/maria-antes-depois.png', 'assets/maria antes e dps pagina 21.png')
$c = $c.replace('assets/como-usar.jpg', 'assets/como usar gelatina mounjaro pagina 22.png')
$c = $c.replace('assets/antes-depois-result.png', 'assets/antes e dps pagina 23.png')
$c = $c.replace('assets/depoimento1.png', 'assets/historia giovanna pagina 27.png')
$c = $c.replace('assets/depoimento2.png', 'assets/historia sandra pagina 27.png')
$c = $c.replace('assets/depoimento3.png', 'assets/historia claudia pagina 27.png')
$c = $c.replace('assets/depoimento4.png', 'assets/historia patricia pagina 27.png')
$c = $c.replace('assets/antes-depois-mulher.png', 'assets/antes e dps pagina 33.png')
$c = $c.replace('assets/gelatina-produto.png', 'assets/pagina 33 oferta.jpg')
$c = $c.replace('assets/garantia30.png', 'assets/garantia 30 dias pagina 33.png')

[IO.File]::WriteAllText("index.html", $c, [Text.Encoding]::UTF8)
